workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 30
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Flutter version
        script: flutter --version
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release --no-shrink
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
